namespace OpenInputManager
{
    public enum AxisNumber
    {
        AxisX,
        AxisY,
        Axis3OrScrollwhell,
        Axis4,
        Axis5,
        Axis6,
        Axis7,
        Axis8,
        Axis9,
        Axis10,
        Axis11,
        Axis12,
        Axis13,
        Axis14,
        Axis15,
        Axis16,
        Axis17,
        Axis18,
        Axis19,
        Axis20,
        Axis21,
        Axis22,
        Axis23,
        Axis24,
        Axis25,
        Axis26,
        Axis27,
        Axis28
    }
}
